// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/kyleterry/jot/pkg/auth"
	"github.com/kyleterry/jot/pkg/config"
	"github.com/kyleterry/jot/pkg/id"
	"github.com/kyleterry/jot/pkg/image"
	"github.com/kyleterry/jot/pkg/image/backend/filesystem"
	"github.com/kyleterry/jot/pkg/jot"
	"github.com/kyleterry/jot/pkg/jot/store/backends"
	"github.com/kyleterry/jot/pkg/server"
)

// Injectors from wire.go:

func initServer() (*server.Server, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	dataDir := provideDataDir(configConfig)
	filesystemOptions := backends.ProvideFilesystemOptions(dataDir)
	backendsFilesystem, err := backends.NewFilesystem(filesystemOptions)
	if err != nil {
		return nil, err
	}
	masterPassword := provideMasterPassword(configConfig)
	seedFileLocation := provideSeedFileLocation(configConfig)
	passwordSpec := auth.DefaultSpec()
	seedFile, err := auth.NewSeedFile(masterPassword, seedFileLocation, passwordSpec)
	if err != nil {
		return nil, err
	}
	v := auth.ProvideAllSeedFiles(seedFile)
	passwordManager := auth.NewPasswordManager(v...)
	idManager, err := id.NewIDManager()
	if err != nil {
		return nil, err
	}
	options := &jot.Options{
		PasswordManager: passwordManager,
		IDManager:       idManager,
	}
	textStore := jot.NewStore(backendsFilesystem, options)
	jotHandler := server.NewJotHandler(configConfig, textStore, passwordManager)
	options2 := &filesystem.Options{
		StorageDir: dataDir,
	}
	backend, err := filesystem.New(options2)
	if err != nil {
		return nil, err
	}
	imageOptions := &image.Options{
		PasswordManager: passwordManager,
		IDManager:       idManager,
	}
	store := image.NewStore(backend, imageOptions)
	imageHandler := server.NewImageHandler(configConfig, store, passwordManager)
	serverServer := server.New(configConfig, jotHandler, imageHandler)
	return serverServer, nil
}

// wire.go:

func provideMasterPassword(cfg *config.Config) auth.MasterPassword {
	return cfg.MasterPassword
}

func provideSeedFileLocation(cfg *config.Config) auth.SeedFileLocation {
	return cfg.SeedFileLocation
}

func provideDataDir(cfg *config.Config) config.DataDir {
	return cfg.DataDir
}
