#!/bin/bash

set -euo pipefail

docker_repo=ghcr.io/kyleterry/jot
docker_cmd=buildah
base_image=docker.io/alpine:latest
archs="amd64 arm32v7 arm64v8"
build_dir=".build"

. ./build-info.sh

build_images() {
    mkdir -p "${build_dir}"

    for arch in ${archs}; do
        goarch=
        bud_args=

        case "${arch}" in
            arm64v*  )
                goarch="arm64"
                bud_args="--override-arch=arm64 --variant=v8"
                ;;
            arm32v*  )
                goarch="arm"
                bud_args="--override-arch=arm --variant=v7"
                ;;
        esac

        GOOS=linux GOARCH="${goarch:-}" CGO_ENABLED=0 go build \
            -installsuffix cgo \
            -o "${build_dir}/jot-${arch}" \
            ./cmd/jot

        GOOS=linux GOARCH="${goarch}" CGO_ENABLED=0 go build \
            -installsuffix cgo \
            -o "${build_dir}/gokey-${arch}" \
            github.com/cloudflare/gokey/cmd/gokey

        chmod +x "${build_dir}"/*

        docker_file="${build_dir}"/Dockerfile."${arch}"
        cp Dockerfile.cross "${docker_file}"

        sed -i "s|__IMAGE__|${base_image}|g" "${docker_file}"
        sed -i "s|__ARCH__|${arch}|g" "${docker_file}"
        sed -i "s|__PLATFORM__|linux/${arch}|g" "${docker_file}"

        version_tag="${docker_repo}":"${VERSION}"-"${arch}"

        ${docker_cmd} bud ${bud_args:-} -f "${docker_file}" -t "${version_tag}" .

        # if [ -z "${DIRTY}" ]; then
        #     ${docker_cmd} push "${version_tag}"
        # fi
    done
}

create_manifest() {
    local version
    version="${1}"

    tag="${docker_repo}":"${version}"

    ${docker_cmd} manifest create "${tag}"
    ${docker_cmd} manifest add "${tag}" "${tag}"-amd64 
    ${docker_cmd} manifest add "${tag}" "${tag}"-arm32v7 
    ${docker_cmd} manifest add "${tag}" "${tag}"-arm64v8
    ${docker_cmd} manifest push --all "${tag}" docker://"${tag}"
}

build_images

if [ -z "${DIRTY}" ]; then
    create_manifest "${VERSION}"
else
    echo -e "\n\nrepository state is dirty\nimages were created but not pushed"
fi
