#!/bin/bash

set -euo pipefail

qemu_static_version="v4.2.0-7"
docker_repo=kyleterry/jot
archs="amd64 arm32v6 arm32v7 arm64v8"
build_dir=".build"

. ./build-info.sh

build_images() {
    mkdir -p "${build_dir}"

    for arch in ${archs}; do
        case "${arch}" in
            amd64   )
                image=alpine
                variant=
                GOARCH=
                ;;
            arm32*  )
                image="${arch}/alpine"
                GOARCH="arm"
                ;;
            arm64*  )
                image="${arch}/alpine"
                GOARCH="arm64"
                ;;
        esac

        GOOS=linux go build \
            -o "${build_dir}/jot-${arch}" \
            ./cmd/jot

        GOOS=linux go build \
            -o "${build_dir}/gokey-${arch}" \
            ./vendor/github.com/cloudflare/gokey/cmd/gokey

        chmod +x "${build_dir}"/*

        docker_file="${build_dir}"/Dockerfile."${arch}"
        cp Dockerfile.cross "${docker_file}"

        sed -i "s|__IMAGE__|${image}|g" "${docker_file}"
        sed -i "s|__ARCH__|${arch}|g" "${docker_file}"

        version_tag="${docker_repo}":"${VERSION}"-"${arch}"

        docker build -f "${docker_file}" -t "${version_tag}" .

        if [ -z "${DIRTY}" ]; then
            docker push "${version_tag}"
        fi

        rm "${docker_file}"
        #rm -f qemu-"${qemu_arch}"-static
    done
}

create_manifest() {
    local version
    version="${1}"

    manifest-tool push from-args \
        --platforms linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 \
        --template kyleterry/jot:"${version}"-ARCHVARIANT \
        --target kyleterry/jot:"${version}"
}

build_images

if [ -z "${DIRTY}" ]; then
    create_manifest "${VERSION}"
else
    echo -e "\n\nrepository state is dirty\nimages were created but not pushed"
fi
