# vim: ft=dockerfile
ARG ARCH=__ARCH__
FROM __IMAGE__
LABEL org.opencontainers.image.source https://github.com/kyleterry/jot
COPY .build/jot-__ARCH__ /bin/jot
COPY .build/gokey-__ARCH__ /bin/gokey
COPY docker-entrypoint.sh /
ENV JOT_SEED_FILE=/etc/jot/seed
ENV JOT_DATA_DIR=/var/lib/jot
VOLUME /etc/jot
VOLUME /var/lib/jot
EXPOSE 8095
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["jot"]
