# vim: ft=dockerfile
FROM --platform=__PLATFORM__ __IMAGE__
RUN apk --no-cache add bash
COPY .build/jot-__ARCH__ /bin/jot
COPY .build/gokey-__ARCH__ /bin/gokey
COPY docker-entrypoint.sh /
ENV JOT_SEED_FILE=/etc/jot/seed
ENV JOT_DATA_DIR=/var/lib/jot
VOLUME /etc/jot
VOLUME /var/lib/jot
EXPOSE 8095
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["jot"]
