package server

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"path"
	"strings"

	"github.com/gorilla/handlers"
	"github.com/kyleterry/jot/pkg/config"
)

const (
	// DefaultContentType is the default content type to use in responses that
	// return the jot content
	DefaultContentType = "text/plain; charset=utf-8"
)

// Server listens to a port on an address as a HTTP server
// and uses gorilla/mux to route requests to HTTP handlers.
type Server struct {
	cfg        *config.Config
	jotRoute   *jotHandler
	imageRoute *imageHandler
}

func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var head string

	head, r.URL.Path = shiftPath(r.URL.Path)

	var next http.Handler

	switch head {
	case "txt":
		next = s.jotRoute
	case "img":
		next = s.imageRoute
	case "favicon.ico":
		next = faviconHandler{}
	case "":
		next = indexHandler{cfg: s.cfg}
	default:
		next = http.HandlerFunc(http.NotFound)
	}

	next.ServeHTTP(w, r)
}

// Run starts an http listener on the configured bind address and returns a cancel
// function and an error channel.
func (s *Server) Run(ctx context.Context) (context.CancelFunc, chan error) {
	ctx, cancel := context.WithCancel(ctx)
	errch := make(chan error, 1)

	logging := handlers.LoggingHandler(os.Stdout, s)
	hsrv := &http.Server{Addr: s.cfg.BindAddr, Handler: logging}
	go func() {
		go s.run(hsrv, errch)

		<-ctx.Done()

		log.Println("shutting down")
		hsrv.Shutdown(ctx)
	}()

	scheme := "http"
	if hsrv.TLSConfig != nil {
		scheme = "https"
	}
	log.Printf("listening on: %s://%s", scheme, hsrv.Addr)

	return cancel, errch
}

func (s *Server) run(srv *http.Server, errch chan<- error) {
	err := srv.ListenAndServe()
	errch <- err
	close(errch)
}

// New returns a new instance of a jot Server with
// the data from the seedFile loaded.
func New(cfg *config.Config, jr *jotHandler, ir *imageHandler) *Server {
	return &Server{
		cfg:        cfg,
		jotRoute:   jr,
		imageRoute: ir,
	}
}

// shiftPath will take a path and pop off each entity at /, creating a head
// and tail. It's used to traverse paths and makes it useful to make branching
// decisions when handling an http request in ServeHTTP methods.
func shiftPath(p string) (head, tail string) {
	p = path.Clean("/" + p)
	i := strings.Index(p[1:], "/") + 1
	if i <= 0 {
		return p[1:], "/"
	}

	return p[1:i], p[i:]
}

// extractHost checks to see if a Host is set in config and returns that, otherwise
// it returns the host generated by net/http.Request.
func extractHost(cfg *config.Config, r *http.Request) string {
	if cfg.Host != "" {
		return cfg.Host
	}

	return fmt.Sprintf("http://%s", r.Host)
}
